# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/build
name: $(Date:yyyyMMdd)$(Rev:.r)
jobs:
- job: buildNugetPackage
  displayName: "Build Package"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    buildConfiguration: 'Release'
  steps:
  - script: dotnet pack --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)"
    displayName: 'dotnet pack --configuration $(buildConfiguration) --output "$(Build.ArtifactStagingDirectory)'
  - publish: "$(Build.ArtifactStagingDirectory)"
    artifact: drop
    displayName: 'Publish Artifact: drop'

- job: publishNugetPackage
  displayName: "Publish Nuget package on ProcessorArtifacts"
  dependsOn: buildNugetPackage
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - download: current
    artifact: drop
  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Pipeline.Workspace)/drop/**/**.nupkg'
      feedsToUse: 'select'
      publishVstsFeed: 'ProcessorArtifacts'